contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://yoursite.example.com/"
canonifyurls = true
title="Etienne Burdet"

[indexes]
   category = "categories"
   tag = "tags"

[Params]
   Description = "City //scientist//geek//enthusiast"
   
[author]
   twitter = "https://twitter.com/GourmetSolitair"
   linkedin = "https://www.linkedin.com/pub/etienne-burdet/16/25b/954"
