contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true
title="Etienne Burdet"
baseurl = "http://etienneburdet.github.io/hugo/"

[indexes]
   category = "categories"
   tag = "tags"

[Author]
  name = "Etienne Burdet"

[Params]
   Description = "Modeling, Analyzing and Enjoying Cities."
   twitter = "https://twitter.com/EtienneBurdet"
   linkedin = "https://www.linkedin.com/pub/etienne-burdet/16/25b/954"
   github = "https://github.com/etienneburdet"
   author = "Etienne Burdet"
