theme = "hyde"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true
title = "Etienne Burdet"
baseurl= "http://etienneburdet.github.io"

[Taxonomies]
   category = "categories"
   tag = "tags"

[Params]
   Description = "Modeling, Analyzing and Enjoying Cities."
   twitter = "https://twitter.com/EtienneBurdet"
   linkedin = "https://www.linkedin.com/pub/etienne-burdet/16/25b/954"
   github = "https://github.com/etienneburdet"
   author = "Etienne Burdet"

[permalinks]
    post = "/:year/:month/:filename/"
    code = "/:filename/"
