contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseurl = "http://yoursite.example.com/"
canonifyurls = true
title="Etienne Burdet"
subtitle="City Enthusiast"

[indexes]
   category = "categories"
   tag = "tags"
